# Generated by Django 5.2.3 on 2025-09-07 10:52

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingest', '0003_articlecontent_and_more'),
        ('semantic', '0001_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestArticleEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, default='intfloat/multilingual-e5-large', max_length=128)),
                ('dim', models.PositiveIntegerField(default=1024, editable=False)),
                ('vector', pgvector.django.vector.VectorField(dimensions=1024)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='ingest.article')),
            ],
            options={
                'verbose_name': 'Article Embedding',
                'verbose_name_plural': 'Article Embeddings',
                'indexes': [models.Index(fields=['model_name'], name='semantic_in_model_n_8aff49_idx')],
                'unique_together': {('article', 'model_name')},
            },
        ),
    ]
