# Generated by Django 5.2.3 on 2025-09-07 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_articlecontent_and_more'),
        ('semantic', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ingestarticleembedding',
            name='semantic_in_model_n_8aff49_idx',
        ),
        migrations.AlterUniqueTogether(
            name='ingestarticleembedding',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ingestarticleembedding',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_e5_large', to='ingest.article'),
        ),
        migrations.RemoveField(
            model_name='ingestarticleembedding',
            name='dim',
        ),
        migrations.RemoveField(
            model_name='ingestarticleembedding',
            name='model_name',
        ),
    ]
