# Generated by Django 5.2.3 on 2025-08-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_preview',
            field=models.URLField(blank=True, null=True),
        ),
    ]
