# Generated by Django 5.2.3 on 2025-08-28 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_article_image_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_html', models.TextField(blank=True, null=True)),
                ('content_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Article Content',
                'verbose_name_plural': 'Article Contents',
            },
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='ingest_arti_site_id_e9595a_idx',
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='ingest_arti_site_id_0682e0_idx',
        ),
        migrations.RemoveField(
            model_name='article',
            name='error_note',
        ),
        migrations.RemoveField(
            model_name='article',
            name='last_crawled_at',
        ),
        migrations.AddField(
            model_name='articlecontent',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='ingest.article'),
        ),
    ]
