# Generated by Django 5.2.3 on 2025-10-23 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingest', '0003_articlecontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('processed', 'Processed'), ('rejected', 'Rejected')], default='created', max_length=20)),
                ('language', models.CharField(choices=[('en', 'EN'), ('ru', 'RU')], default='ru', max_length=2)),
                ('source_ingest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ideas', to='ingest.article')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.articleidea')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_name', models.CharField(max_length=100)),
                ('result', models.JSONField(blank=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='article.articleidea')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='articleidea',
            constraint=models.CheckConstraint(condition=models.Q(('source_ingest__isnull', False), models.Q(('title__isnull', False), models.Q(('title', ''), _negated=True)), _connector='OR'), name='articleidea_title_or_ingest_required'),
        ),
    ]
