# Generated by Django 5.2.3 on 2025-10-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleidea',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articleidea',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('processed', 'Processed'), ('error', 'Error'), ('rejected', 'Rejected')], default='created', max_length=20),
        ),
    ]
