# Generated by Django 5.2.3 on 2025-10-30 18:32

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articleidea_content_alter_articleidea_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=article.models.article_image_upload_path),
        ),
    ]
