# Generated by Django 5.2.3 on 2025-10-31 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleProcess',
            new_name='ArticleAgentProcess',
        ),
    ]
