# Generated by Django 5.2.3 on 2025-10-31 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_rename_articleprocess_articleagentprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTextAnalysis',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('unique', models.FloatField(blank=True, null=True)),
                ('count_chars_with_space', models.IntegerField(blank=True, null=True)),
                ('count_chars_without_space', models.IntegerField(blank=True, null=True)),
                ('count_words', models.IntegerField(blank=True, null=True)),
                ('water_percent', models.IntegerField(blank=True, null=True)),
                ('spam_percent', models.IntegerField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
            ],
            options={
                'verbose_name': 'Text analysis',
                'verbose_name_plural': 'Text analyses',
            },
        ),
    ]
