# Generated by Django 5.2.3 on 2025-10-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_articletextanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletextanalysis',
            name='uid',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
