# Generated by Django 5.2.3 on 2025-10-31 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_articletextanalysis_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletextanalysis',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='article.article'),
        ),
    ]
