# Generated by Django 5.2.3 on 2025-11-01 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_alter_articletextanalysis_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleWebTextAnalysis',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('unique', models.FloatField(blank=True, null=True)),
                ('count_chars_with_space', models.IntegerField(blank=True, null=True)),
                ('count_chars_without_space', models.IntegerField(blank=True, null=True)),
                ('count_words', models.IntegerField(blank=True, null=True)),
                ('water_percent', models.IntegerField(blank=True, null=True)),
                ('spam_percent', models.IntegerField(blank=True, null=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='web_text_analysis', to='article.article')),
            ],
            options={
                'verbose_name': 'Text analysis',
                'verbose_name_plural': 'Text analyses',
            },
        ),
        migrations.DeleteModel(
            name='ArticleTextAnalysis',
        ),
    ]
